resource_group_name     = "rg-terraform-web-sql-db"
resource_group_location = "centralindia"
app_service_plan_name   = "cld-appserviceplan-web-21"
app_service_name        = "cld-terraform-web-021"
sql_server_name         = "cld-terraform-sqlserver-021"
sql_database_name       = "ProductsDB"
sql_admin_login         = "user01"
sql_admin_password      = "@Aa123456789!"